// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TeamHeartFiap.Infrastructure.Data;

#nullable disable

namespace TeamHeartFiap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201003117_CriacaoInicialOracle")]
    partial class CriacaoInicialOracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamHeartFiap.Domain.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Demografico")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PrioridadeDiversidade")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("CANDIDATOS", (string)null);
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.ConclusaoTreinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("TreinamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TreinamentoId");

                    b.HasIndex("CandidatoId", "TreinamentoId")
                        .IsUnique();

                    b.ToTable("CONCLUSAO_TREINAMENTO", (string)null);
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.MetricaDiversidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Contagem")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("METRICAS_DIVERSIDADE", (string)null);
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.Treinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Titulo")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TREINAMENTOS", (string)null);
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.ConclusaoTreinamento", b =>
                {
                    b.HasOne("TeamHeartFiap.Domain.Candidato", "Candidato")
                        .WithMany("ConclusoesTreinamento")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamHeartFiap.Domain.Treinamento", "Treinamento")
                        .WithMany("ConclusoesTreinamento")
                        .HasForeignKey("TreinamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Treinamento");
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.Candidato", b =>
                {
                    b.Navigation("ConclusoesTreinamento");
                });

            modelBuilder.Entity("TeamHeartFiap.Domain.Treinamento", b =>
                {
                    b.Navigation("ConclusoesTreinamento");
                });
#pragma warning restore 612, 618
        }
    }
}
